---
-  hosts: all
   tasks:
     - name: Ansible for loop
       debug:
         msg: >
                 {% for entry in ansible_all_ipv4_addresses | default('') -%}
                     IP Address entry {{ loop.index }} = {{ entry }}
                  {% endfor %}
