---
-  hosts: webserver
   become: true
   tasks:
     - name: Install web components
       apt: name={{ item }} state=present update_cache=yes
       with_items:
         - apache2
         - libapache2-mod-wsgi
         - python-pip
         - python-virtualenv
         - python-mysqldb

     - name: Ensure apache2 is started
       service: name=apache2 state=started enabled=yes

     - name: Verify apache2 is really started or not
       command: service apache2 status

     - name: Ensure mod_wsgi enabled
       apache2_module: name=wsgi state=present
       notify: restart apache2

     - name: Copy Practice folder
       copy: src=/root/ansible/practice/ dest=/var/www/html mode=0755
       notify: restart apache2

     - name: Copy ansible.html file
       copy: src=/root/ansible/practice/ansible.html dest=/etc/apache2/sites-available mode=0755
       notify: restart apache2
 
     - name: Deactivate apache default site
       file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
       notify: restart apache2

     - name: Activate ansible.html
       file: src=/etc/apache2/sites-available/ansible.html dest=/etc/apache2/sites-enabled/ansible.html state=link
       notify: restart apache2

   handlers:
     - name: restart apache2
       service: name=apache2 state=restarted
